# Use the official Node.js image as the base image
FROM node:16

# Create and change to the app directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Install development dependencies
RUN npm install --force

# Expose the port the app runs on
EXPOSE 3000

# Install wait-on globally
RUN npm install -g wait-on

# Define the command to run the application
CMD ["sh", "-c", "wait-on tcp:6379 && npm run start:dev"]
